name: CI

on:
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7.5
          - 3.1.6
        rails:
          - 6.1.7.8
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake test
